usb: Gadget: fix unused-function warning
../drivers/usb/gadget/configfs.c:1503:12: error: unused function 'configfs_composite_setup' [-Werror,-Wunused-function]
static int configfs_composite_setup(struct usb_gadget *gadget,
           ^
../drivers/usb/gadget/configfs.c:1528:13: error: unused function 'configfs_composite_disconnect' [-Werror,-Wunused-function]
static void configfs_composite_disconnect(struct usb_gadget *gadget)

Those functions are being used when CONFIG_USB_CONFIGFS_UEVENT is not defined, so wrap them between
macros in order to avoid that error.

Patch from commit: 0c53ca576b80d37604424a47983f5b57ba4b4705 from
https://review.lineageos.org/q/project:LineageOS%252Fandroid_kernel_xiaomi_sdm845+branch:staging%252Flineage-17.0+status:merged